### ISSUE TITLE
[Detectron2] RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by vztu** [ericsujw/InstColorization#27]
Hi, 

Thanks for the great work! I am reproducing your work following [README_TRAIN.md](https://github.com/ericsujw/InstColorization/blob/master/README_TRAIN.md) step by step, but encountered an error while running the [Instance Prediction](https://github.com/ericsujw/InstColorization#instance-prediction) step:
```
sh scripts/prepare_train_box.sh
```
The error I got was:
```
Traceback (most recent call last):
  File "inference_bbox.py", line 51, in <module>
    outputs = predictor(l_stack)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 218, in __call__
    predictions = self.model([inputs])[0]
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in inference
    features = self.backbone(images.tensor)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/modeling/backbone/fpn.py", line 123, in forward
    bottom_up_features = self.bottom_up(x)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 454, in forward
    x = self.stem(x)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ztu/miniconda3/envs/instacolorization/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 391, in forward
    x = F.relu_(x)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
Do you know how to fix this problem? Thanks!

**Comment by vztu** [comment]
Fixed by pip install Detectron2 with CUDA=11.0, Torch=1.7
ref: https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#install-pre-built-detectron2-linux-only
(hardware: RTX 3070)
